[theme]
primaryColor = "#1d9bf0"
backgroundColor = "#0f1419"
secondaryBackgroundColor = "#15202b"
textColor = "#e7e9ea"
font = "sans serif"

[server]
runOnSave = true

[browser]
gatherUsageStats = false

[client]
showErrorDetails = false
toolbarMode = "minimal"

[runner]
fastReruns = true
